name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  robot-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install robotframework
        pip install robotframework-browser

    - name: Install Playwright browsers
      run: |
        rfbrowser init

    - name: Run Robot Framework tests headless
      run: |
        robot --variable HEADLESS:True -d results tests/

     # 5️⃣ Maak de map voor testresultaten
    - name: Create results directory
      run: mkdir -p results

    # 6️⃣ Run alle tests in tests/ map
    - name: Run RobotFramework tests
      run: |
        robot -d results tests/

    # 7️⃣ Upload de testresultaten als artifacts
    - name: Upload RobotFramework results
      if: always()          # <--- dit zorgt dat artifacts altijd geüpload worden, zelfs bij test failures
      uses: actions/upload-artifact@v4
      with:
        name: robot-results
        path: results/